INSERT INTO user (ID, CREATED_BY,CREATED_ON,DELETED_ON,UPDATED_BY,UPDATED_ON,VERSION,ACCOUNT_EXPIRED,ACCOUNT_LOCKED,CREDENTIALS_EXPIRED,EMAIL,ENABLED,PASSWORD,USERNAME)
VALUES           (1, 1,CURRENT_TIMESTAMP(),'2019-10-12 16:05:19.857',1, CURRENT_TIMESTAMP(),1,false,false,false,'user@usser.com', true,'$2a$10$dEkypMiKfP.S.JPGovEb1.lQa7M/2M7mjJtmb/E/KychMifBqx1ku', 'user');


INSERT INTO ROLE (ID, CREATED_BY,CREATED_ON,DELETED_ON, UPDATED_BY, UPDATED_ON, VERSION, NAME)
VALUES           (1, 1,CURRENT_TIMESTAMP(),'2019-10-12 16:05:19.857',1, CURRENT_TIMESTAMP(),1,'ROLE_TRUSTED');

INSERT INTO ROLE_USER (USER_ID, ROLE_ID)
VALUES           (1, 1);

INSERT INTO PERMISSION (ID, CREATED_BY,CREATED_ON,DELETED_ON, UPDATED_BY, UPDATED_ON, VERSION, NAME)
VALUES           (1, 1,CURRENT_TIMESTAMP(),'2019-10-12 16:05:19.857',1, CURRENT_TIMESTAMP(),1,'ROLE_TRUSTED');

INSERT INTO PERMISSION_ROLE (ROLE_ID, PERMISSION_ID)
VALUES           (1, 1);

